# Generated by Django 3.2 on 2025-07-01 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level', 'name'],
                'unique_together': {('name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Organigram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final'), ('Archived', 'Archived')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mission_principal', models.TextField()),
                ('abbreviation', models.CharField(blank=True, max_length=255, null=True)),
                ('formation', models.CharField(default='', max_length=255)),
                ('experience', models.CharField(default='', max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('initial_node', models.BooleanField(default=False)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='organigramme.grade')),
                ('organigram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organigramme.organigram')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organigramme.position')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrganigramEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(default='smoothstep', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organigram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='organigramme.organigram')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='organigramme.position')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='organigramme.position')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='organigramme.position')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='organigramme.position')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['organigram'], name='organigramm_organig_bfd2de_idx'),
        ),
        migrations.AddIndex(
            model_name='organigramedge',
            index=models.Index(fields=['organigram'], name='organigramm_organig_35c615_idx'),
        ),
        migrations.AddIndex(
            model_name='organigramedge',
            index=models.Index(fields=['source'], name='organigramm_source__19e4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='organigramedge',
            index=models.Index(fields=['target'], name='organigramm_target__06ad54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organigramedge',
            unique_together={('source', 'target')},
        ),
    ]
