# Generated by Django 3.2 on 2025-07-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mission_principal', models.TextField(default='')),
                ('abbreviation', models.CharField(blank=True, max_length=255, null=True)),
                ('formation', models.CharField(default='', max_length=255)),
                ('experience', models.CharField(default='', max_length=255)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('initial_node', models.BooleanField(default=False)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='organigramme.grade')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organigramme.position')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final'), ('Archived', 'Archived')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organigramme.structure')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='position',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organigramme.structure'),
        ),
        migrations.CreateModel(
            name='OrganigramEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField()),
                ('target_object_id', models.PositiveIntegerField()),
                ('edge_type', models.CharField(default='smoothstep', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_edges', to='contenttypes.contenttype')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='organigramme.structure')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_edges', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='organigramme.position')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='organigramme.position')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['structure'], name='organigramm_structu_285903_idx'),
        ),
        migrations.AddIndex(
            model_name='organigramedge',
            index=models.Index(fields=['structure'], name='organigramm_structu_3030b1_idx'),
        ),
        migrations.AddIndex(
            model_name='organigramedge',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='organigramm_source__371aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='organigramedge',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='organigramm_target__3b40f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organigramedge',
            unique_together={('source_content_type', 'source_object_id', 'target_content_type', 'target_object_id')},
        ),
    ]
