# Generated by Django 3.2 on 2025-07-14 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organigramme.structure'),
        ),
    ]
