# Generated by Django 3.2 on 2025-06-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['title']},
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='organigramm_organig_809aec_idx',
        ),
        migrations.RemoveField(
            model_name='position',
            name='color',
        ),
        migrations.RemoveField(
            model_name='position',
            name='level',
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['organigram'], name='organigramm_organig_bfd2de_idx'),
        ),
    ]
