# Generated by Django 3.2 on 2025-07-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='state',
        ),
        migrations.AddField(
            model_name='structure',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
