# Generated by Django 3.2 on 2025-07-01 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='organigram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organigramme.organigram'),
        ),
    ]
