# Generated by Django 3.2 on 2025-07-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0002_alter_position_organigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
