# Generated by Django 3.2 on 2025-07-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0002_auto_20250707_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='structure',
            name='position_y',
            field=models.FloatField(default=0),
        ),
    ]
