# Generated by Django 3.2 on 2025-06-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0003_competence_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='experience',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='position',
            name='formation',
            field=models.CharField(default='', max_length=255),
        ),
    ]
