# Generated by Django 3.2 on 2025-07-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0003_auto_20250709_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructurePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0, help_text='X position in the organigram')),
                ('position_y', models.FloatField(default=0, help_text='Y position in the organigram')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organigram', models.ForeignKey(help_text='The organigram view this position is for', on_delete=django.db.models.deletion.CASCADE, related_name='positioned_structures', to='organigramme.structure')),
                ('structure', models.ForeignKey(help_text='The structure being positioned', on_delete=django.db.models.deletion.CASCADE, related_name='structure_positions', to='organigramme.structure')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('structure', 'organigram')},
            },
        ),
    ]
