# Generated by Django 3.2 on 2025-07-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0003_auto_20250714_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='position',
            name='formation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='position',
            name='mission_principal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='structure',
            unique_together=set(),
        ),
    ]
