# Generated by Django 3.2 on 2025-07-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0004_structureposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='position_y',
        ),
        migrations.DeleteModel(
            name='StructurePosition',
        ),
    ]
