# Generated by Django 3.2 on 2025-07-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0004_auto_20250630_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='position',
            name='mission_principal',
            field=models.TextField(default='ereé'),
            preserve_default=False,
        ),
    ]
