# Generated by Django 3.2 on 2025-07-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0005_auto_20250709_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='position',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='organigramm_structu_285903_idx',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position_y',
        ),
        migrations.AddField(
            model_name='positionlayout',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='organigramme.position'),
        ),
        migrations.AddField(
            model_name='positionlayout',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_layouts', to='organigramme.structure'),
        ),
        migrations.AddIndex(
            model_name='positionlayout',
            index=models.Index(fields=['structure'], name='organigramm_structu_57dfee_idx'),
        ),
    ]
