# Generated by Django 3.2 on 2025-07-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0005_auto_20250701_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='category',
            field=models.CharField(default='C5', max_length=20),
            preserve_default=False,
        ),
    ]
