# Generated by Django 3.2 on 2025-07-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0006_auto_20250709_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionlayout',
            name='position',
        ),
        migrations.RemoveField(
            model_name='positionlayout',
            name='structure',
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='position',
            name='position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='position_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['structure'], name='organigramm_structu_285903_idx'),
        ),
        migrations.DeleteModel(
            name='PositionLayout',
        ),
    ]
