# Generated by Django 3.2 on 2025-07-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0006_grade_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='grade',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='organigramme.grade'),
        ),
    ]
