# Generated by Django 3.2 on 2025-07-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0007_alter_position_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
