# Generated by Django 3.2 on 2025-07-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organigramme', '0007_auto_20250710_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('main_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagram_positions', to='organigramme.structure')),
            ],
        ),
        migrations.AddIndex(
            model_name='diagramposition',
            index=models.Index(fields=['content_type', 'object_id'], name='organigramm_content_e445a0_idx'),
        ),
        migrations.AddIndex(
            model_name='diagramposition',
            index=models.Index(fields=['main_structure'], name='organigramm_main_st_1b6bea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diagramposition',
            unique_together={('content_type', 'object_id', 'main_structure')},
        ),
    ]
