# Generated by Django 3.2 on 2025-07-12 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0008_auto_20250710_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Whether this position is a manager position'),
        ),
        migrations.AddField(
            model_name='structure',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_structures', to='organigramme.position'),
        ),
    ]
