# Generated by Django 3.2 on 2025-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='layout_preference',
            field=models.CharField(choices=[('top', 'Top'), ('side', 'Side')], default='top', max_length=4),
        ),
    ]
